# workflows:
#   android-workflow:
#     name: Android Workflow
#     triggering:
#       events:
#         - push
#         - pull_request
#       branch_patterns:
#         - pattern: 'main'
#           include: true
#           source: true
#     max_build_duration: 60
#     environment:
#       flutter: stable
#       android_signing:
#         - selc
#       vars:
#         KEYSTORE_PATH: selc.jks
#         KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
#         KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
#         KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#     scripts:
#       - name: Set up keystore
#         script: |
#           echo $KEYSTORE_PASSWORD | base64 --decode > $KEYSTORE_PATH
#           echo "storePassword=$KEYSTORE_PASSWORD" > key.properties
#           echo "keyPassword=$KEY_PASSWORD" >> key.properties
#           echo "keyAlias=$KEY_ALIAS" >> key.properties
#           echo "storeFile=$KEYSTORE_PATH" >> key.properties
#       - name: Set up local.properties
#         script: |
#           echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
#       - name: Get Flutter packages
#         script: |
#           flutter packages pub get
#       - name: Create .env file
#         script: |
#           echo "API_KEY=$API_KEY" > .env
#           echo "SECRET_TOKEN=$SECRET_TOKEN" >> .env
#       - name: Build AAB
#         script: |
#           flutter build appbundle --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
#     artifacts:
#       - build/**/outputs/**/*.aab
#     publishing:
#       google_play:
#         credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#         track: internal


definitions:
  scripts:
    - &shorebird_install
      name: Install Shorebird CLI
      script: |
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
        echo PATH="/Users/builder/.shorebird/bin:$PATH" >> $CM_ENV        
    - &flutter_analyze
      name: Run static code analysis
      script: flutter analyze
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

workflows:
  android-release-workflow:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - keystore_credentials  # Contains: CM_KEYSTORE, CM_KEY_ALIAS, CM_KEY_PASSWORD, CM_KEYSTORE_PASSWORD
        - app_secrets          # Contains: GOOGLE_SERVICES_JSON, ADMIN_PASSWORD, ADMIN_PHONE_NUMBER
      vars:
        PACKAGE_NAME: "com.sairatec.selc"
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Add this to CodeMagic encrypted variables
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}  # Add your Android app ID from Firebase
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_BUILD_DIR/keystore.jks
          EOF
      
      - *setup_local_properties
      
      - *flutter_analyze
      
      - name: Set up Google Services
        script: |
          echo "$GOOGLE_SERVICES_JSON" > "$CM_BUILD_DIR/android/app/google-services.json"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash
      
      - name: Build APK
        script: |
          flutter build apk --release
      
      - name: Upload to Firebase App Distribution
        script: |
          if [[ $FCI_BUILD_TYPE == "release" ]]; then
            firebase appdistribution:distribute "build/app/outputs/flutter-apk/app-release.apk" \
              --app "$FIREBASE_APP_ID" \
              --token "$FIREBASE_TOKEN" \
              --groups "testers" \
              --release-notes "New build from CodeMagic CI/CD"
          fi
      
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/**/outputs/**/*.aab
    
    publishing:
      email:
        recipients:
          - wasimxaman13@gmail.com
