definitions:
  environment:
    shared_env: &shared_env
      flutter: 3.24.1
      groups:
        - keystore_credentials
        - app_secrets
      vars:
        FLUTTER_VERSION: 3.24.1
        PACKAGE_NAME: "com.sairatec.selc"
  scripts:
    - &shorebird_install
      name: Install Shorebird
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
        # Add Shorebird to PATH
        echo 'export PATH="$HOME/.shorebird/bin:$PATH"' >> $CM_ENV
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    - &create_env_file
      name: Create .env file
      script: |
        cat > .env << EOF
        # Admin
        ADMIN_PHONE_NUMBER=$ADMIN_PHONE_NUMBER
        ADMIN_PASSWORD=$ADMIN_PASSWORD
        EOF

workflows:
  android-release-workflow:
    name: Android Release Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      <<: *shared_env
      android_signing:
        - android_keystore
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - *create_env_file
      
      - name: Set up keystore
        script: |
          echo "$CM_KEYSTORE" | base64 --decode > "$CM_BUILD_DIR/selc.jks"
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=${CM_KEYSTORE_PASSWORD}
          keyPassword=${CM_KEY_PASSWORD}
          keyAlias=selc
          storeFile=${CM_BUILD_DIR}/selc.jks
          EOF
      
      - *setup_local_properties
      
      - name: Set up Google Services
        script: |
          echo "$GOOGLE_SERVICES_JSON" > "$CM_BUILD_DIR/android/app/google-services.json"
      
      - name: Install Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash
      
      - *shorebird_install
      
      - name: Shorebird Login and Release
        script: |
          # Source the environment to get Shorebird in PATH
          source $CM_ENV
          # Login to Shorebird
          echo "$SHOREBIRD_TOKEN" > shorebird_token.txt
          shorebird login --token "$(cat shorebird_token.txt)"
          rm shorebird_token.txt
          
          # Get the latest build number from Firebase
          BUILD_NUMBER=$(($(firebase appdistribution:get-latest-build-number --app "$FIREBASE_APP_ID" --token "$FIREBASE_TOKEN") + 1))
          
          # Release with Shorebird
          shorebird release android --flutter-version="$FLUTTER_VERSION"
      
      - name: Upload to Firebase App Distribution
        script: |
          # Find the generated AAB file
          AAB_PATH=$(find build -name "*.aab" | head -n 1)
          
          # Upload to Firebase
          firebase appdistribution:distribute "$AAB_PATH" \
            --app "$FIREBASE_APP_ID" \
            --token "$FIREBASE_TOKEN" \
            --groups "testers" \
            --release-notes "Build $BUILD_NUMBER from Shorebird via CodeMagic CI/CD"
    
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - wasimxaman13@gmail.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  patch-android-workflow:
    name: Patch Android
    instance_type: mac_mini_m1
    environment:
      <<: *shared_env
      android_signing:
        - android_keystore
    inputs:
      release_version:
        description: The release version to patch
    scripts:
      - *shorebird_install
      - *create_env_file
      - name: Shorebird Patch
        script: |
          source $CM_ENV
          echo "$SHOREBIRD_TOKEN" > shorebird_token.txt
          shorebird login --token "$(cat shorebird_token.txt)"
          rm shorebird_token.txt
          shorebird patch android --release-version=${{ inputs.release_version }}
