definitions:
  scripts:
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    
    - &create_env_file
      name: Create .env file
      script: |
        cat > .env << EOF
        # Admin credentials
        ADMIN_PHONE_NUMBER=$ADMIN_PHONE_NUMBER
        ADMIN_PASSWORD=$ADMIN_PASSWORD
        EOF
    
    - &setup_keystore
      name: Set up keystore and properties
      script: |
        # Decode and save keystore
        echo "$CM_KEYSTORE" | base64 --decode > "$CM_BUILD_DIR/selc.jks"
        # Create key.properties
        cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_PASSWORD
        keyAlias=$CM_KEY_ALIAS
        storeFile=$CM_BUILD_DIR/selc.jks
        EOF
    
    - &setup_firebase
      name: Set up Firebase configuration
      script: |
        # Set up google-services.json
        echo "$GOOGLE_SERVICES_JSON" > "$CM_BUILD_DIR/android/app/google-services.json"
    
    - &build_and_distribute
      name: Build APK and Distribute
      script: |
        # Get dependencies
        flutter pub get
        
        # Build release APK
        flutter build apk \
          --release \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER
        
        # Install Firebase CLI
        curl -sL https://firebase.tools | bash
        
        # Distribute to Firebase
        firebase appdistribution:distribute \
          "build/app/outputs/apk/release/app-release.apk" \
          --app "$FIREBASE_APP_ID" \
          --token "$FIREBASE_TOKEN" \
          --groups "pre-tester" \
          --release-notes "Build $BUILD_NUMBER via CodeMagic CI/CD"

workflows:
  android-release-workflow:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      flutter: 3.24.3
      groups:
        - keystore_credentials
        - app_secrets
      vars:
        PACKAGE_NAME: "com.sairatec.selc"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - *create_env_file
      - *setup_local_properties
      - *setup_keystore
      - *setup_firebase
      - *build_and_distribute
    
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
    
    publishing:
      email:
        recipients:
          - wasimxaman13@gmail.com
