definitions:
  scripts:
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    
    - &create_env_file
      name: Create .env file
      script: |
        cat > .env << EOF
        # Admin credentials
        ADMIN_PHONE_NUMBER=$ADMIN_PHONE_NUMBER
        ADMIN_PASSWORD=$ADMIN_PASSWORD
        EOF
    
    - &setup_keystore
      name: Set up keystore
      script: |
        echo "$CM_KEYSTORE" | base64 --decode > "$CM_BUILD_DIR/selc.jks"
        cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_PASSWORD
        keyAlias=selc
        storeFile=$CM_BUILD_DIR/selc.jks
        EOF
    
    - &setup_google_services
      name: Set up Google Services
      script: |
        echo "$GOOGLE_SERVICES_JSON" > "$CM_BUILD_DIR/android/app/google-services.json"
    
    - &build_and_distribute
      name: Build and Distribute AAB
      script: |
        # Get Flutter dependencies
        flutter pub get
        
        # Build the app bundle
        flutter build appbundle \
          --release \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER
        
        # Install Firebase CLI
        curl -sL https://firebase.tools | bash
        
        # Upload to Firebase App Distribution
        firebase appdistribution:distribute \
          "build/app/outputs/bundle/release/app-release.aab" \
          --app "$FIREBASE_APP_ID" \
          --token "$FIREBASE_TOKEN" \
          --groups "testers" \
          --release-notes "Build $BUILD_NUMBER via CodeMagic CI/CD"

workflows:
  android-release-workflow:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      flutter: 3.24.3
      groups:
        - keystore_credentials
        - app_secrets
      vars:
        PACKAGE_NAME: "com.sairatec.selc"
        FIREBASE_TOKEN: $FIREBASE_TOKEN
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        ADMIN_PHONE_NUMBER: $ADMIN_PHONE_NUMBER
        ADMIN_PASSWORD: $ADMIN_PASSWORD
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - *create_env_file
      - *setup_local_properties
      - *setup_keystore
      - *setup_google_services
      - *build_and_distribute
    
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    
    publishing:
      email:
        recipients:
          - wasimxaman13@gmail.com
