// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK49EvvEpcAd8TkAG9vxcXrTFREgB4jp8',
    appId: '1:319566026734:web:46ddfbf1298751dd81a0ff',
    messagingSenderId: '319566026734',
    projectId: 'selc-1e9aa',
    authDomain: 'selc-1e9aa.firebaseapp.com',
    storageBucket: 'selc-1e9aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOlKwz48e6Odb73w61KvYWOoLzQboPK3I',
    appId: '1:319566026734:android:8b75d2c1cacdea4881a0ff',
    messagingSenderId: '319566026734',
    projectId: 'selc-1e9aa',
    storageBucket: 'selc-1e9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSflhiXSI4zMl_2KlJQZzY_4Qt7x6ler8',
    appId: '1:319566026734:ios:42fccd10c60d748c81a0ff',
    messagingSenderId: '319566026734',
    projectId: 'selc-1e9aa',
    storageBucket: 'selc-1e9aa.appspot.com',
    iosBundleId: 'com.sairatec.selc',
  );
}
